### ISSUE TITLE
Diagnostics mode / Support mode

### ISSUE THREAD

**Issue by ToeiRei** [OpenTails/tail_app#216]
2 Scenarios I see big use in:

1) End user (guide them through with yes/no)
- Let the end user see if their stuff works and what does not (+ support mail thing?)
- test servo movement (just do a slow move on every servo)
- see if mic work on eg2
- detect glow tip (ask: did you pay for it?)
- ...

2) Support people
- test if gear is fixed correctly
- get an overview on what you have in your hands
- forget gear on disconnect

**Comment by MasterTailer** [comment]
We get literally no support questions apart from either

- im trying to pair my gear (but my bluetooth is off, fixed)
- my tail wags one way (theyve broken a servo)

This is a nice idea, but its not something we need to do.

And lastly, eargear mics dont work as well we we want. We dont need a support mode to know this unfortunately. Being fixed in the new pcb spin up. This is not something we can emphasise now though. Lets not spend time on this for now. We are fortunate that almost all issues can be fixed without the app (ie system bluetooth/location services) or busted servo.

**Comment by MasterTailer** [comment]
Just chatted with @ToeiRei about this - its important that **we dont present technical details to customers** at any point of their experience, and so I need to put a veto on this, if Ive understood the proposal correctly.

If its to create some kind of diagnostic suite behind a dev wall, then ok, although Im not sure how that would help, though Im open to discussing it.
